package cotizacion.model;
// Generated 29/06/2018 09:54:02 AM by Hibernate Tools 4.3.1



/**
 * Socios generated by hbm2java
 */
public class Socios  implements java.io.Serializable {


     private Integer idSocio;
     private String nombreSocio;
     private Double tasaInteres;
     private String montoDisponible;

    public Socios() {
    }

    public Socios(String nombreSocio, Double tasaInteres, String montoDisponible) {
       this.nombreSocio = nombreSocio;
       this.tasaInteres = tasaInteres;
       this.montoDisponible = montoDisponible;
    }
   
    public Integer getIdSocio() {
        return this.idSocio;
    }
    
    public void setIdSocio(Integer idSocio) {
        this.idSocio = idSocio;
    }
    public String getNombreSocio() {
        return this.nombreSocio;
    }
    
    public void setNombreSocio(String nombreSocio) {
        this.nombreSocio = nombreSocio;
    }
    public Double getTasaInteres() {
        return this.tasaInteres;
    }
    
    public void setTasaInteres(Double tasaInteres) {
        this.tasaInteres = tasaInteres;
    }
    public String getMontoDisponible() {
        return this.montoDisponible;
    }
    
    public void setMontoDisponible(String montoDisponible) {
        this.montoDisponible = montoDisponible;
    }




}


